#pragma once

#include <vector>
#include <string>

enum class SCRIPT_TYPE
{
	ACTORSCRIPT,
	ATTACKIMPACTSCRIPT,
	BATSCRIPT,
	BAZOOKABULLET,
	BAZOOKASCRIPT,
	BOSSSCRIPT,
	CAMERASCRIPT,
	CASTLEBULLET,
	CASTLESCRIPT,
	CROWBATBULLET,
	CROWBULLET,
	CROWEGGBULLET,
	CROWSCRIPT,
	EFFECTSCRIPT,
	ENDING,
	EXPLOSIONPARTICLE,
	FADESCRIPT,
	FIREDAMAGEPARTICLE,
	HPBAR,
	IRONMACESCRIPT,
	MAPCHANGE,
	MAPGIMIC,
	MEMORYPOOLSCRIPT,
	MONSTERSCRIPT,
	NAILSCRIPT,
	PLANTBULLET,
	PLANTSCRIPT,
	PLAYERARROW,
	PLAYERBOMB,
	PLAYERCHAIN,
	PLAYERHOOK,
	PLAYERMAGIC,
	PLAYERSCRIPT,
	PROJECTILE,
	RANDOMMGRSCRIPT,
	SCENECHANGE,
	SKULLBULLET,
	SKULLSCRIPT,
	SKYBOXSCRIPT,
	SLASHEFFECT,
	SPEARMANSCRIPT,
	SPIDERSCRIPT,
	TESTMONSTERATTACKEFFECT,
	TESTMONSTERSCRIPT,
	TITLE,
	TONGUEBULLET,
	TONGUESCRIPT,
	UPDOWNSWITCH,
	WEAPONTYPE,
	END,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
